feat: flatpak support
cosmic-utils/tweaks pull request #23
Opened 2024-09-24 18:45 UTC by wiiznokes

2024-09-24 18:53 UTC, wiiznokes commented
note that it may be preferable to create the flatpak repo now @edfloreshz, and i can create a pull request there to avoid merging the big `cargo-sources.json`. But you can already test the flatpak with this branch.

2024-09-24 18:55 UTC, edfloreshz commented
On second thought, could you change `dev.edfloreshz.Tweaks` to `dev.edfloreshz.CosmicTweaks`? Given that this is a COSMIC specific app, i think it would be a better fit.

Sorry about that 😅

2024-09-24 18:57 UTC, edfloreshz commented
I'm currently traveling 🧳 , it may be a while before I can create the repository, we can hold this PR until then.

2024-09-24 18:58 UTC, wiiznokes commented
Yeah np

2024-09-24 19:07 UTC, edfloreshz commented
Perfect! I'll review when I'm on my laptop 💻 thanks

2024-09-28 21:35 UTC, edfloreshz commented
I'm reviewing the PR, could you rebase it with the latest changes?

2024-09-28 21:36 UTC, edfloreshz commented on cargo-sources.json
Should this file be pushed?

2024-09-28 21:39 UTC, edfloreshz commented on res/metainfo.xml
> +  <url type="homepage">https://github.com/edfloreshz/cosmic-tweaks</url>
```suggestion
  <url type="homepage">https://github.com/cosmic-utils/tweaks</url>
```

2024-09-28 21:39 UTC, edfloreshz commented on res/metainfo.xml
> +  <url type="bugtracker">https://github.com/edfloreshz/cosmic-tweaks/issues</url>
```suggestion
  <url type="bugtracker">https://github.com/cosmic-utils/tweaks/issues</url>
```

2024-09-28 21:40 UTC, edfloreshz commented on res/metainfo.xml
> +        https://raw.githubusercontent.com/edfloreshz/cosmic-tweaks/main/res/screenshots/window-light.png</image>
```suggestion
        https://raw.githubusercontent.com/cosmic-utils/tweaks/main/res/screenshots/window-light.png</image>
```

2024-09-28 21:41 UTC, edfloreshz commented on res/metainfo.xml
> +        https://raw.githubusercontent.com/edfloreshz/cosmic-tweaks/main/res/screenshots/window-dark.png</image>
```suggestion
        https://raw.githubusercontent.com/cosmic-utils/tweaks/main/res/screenshots/window-dark.png</image>
```

2024-09-28 21:41 UTC, edfloreshz commented on res/metainfo.xml
> +    https://raw.githubusercontent.com/edfloreshz/cosmic-tweaks/master/res/app_icon.svg</icon>
```suggestion
    https://raw.githubusercontent.com/cosmic-utils/tweaks/master/res/app_icon.svg</icon>
```

2024-09-28 21:43 UTC, edfloreshz requested changes
Some minor changes

2024-09-28 22:29 UTC, wiiznokes commented
> I'm reviewing the PR, could you rebase it with the latest changes?

Done

2024-09-28 22:30 UTC, wiiznokes commented on cargo-sources.json
Probably not, see https://github.com/cosmic-utils/tweaks/pull/23#issuecomment-2372062956

2024-09-28 22:42 UTC, edfloreshz commented
I'll try to make the Flathub repo tomorrow.

2024-09-29 03:26 UTC, edfloreshz commented on cargo-sources.json
Can you remove this file? I'm creating the repo but I need to merge this first.

2024-09-29 03:32 UTC, edfloreshz commented on cargo-sources.json
You can go ahead and delete it, I already pushed it to https://github.com/edfloreshz/flathub/tree/dev.edfloreshz.CosmicTweaks

2024-09-29 03:36 UTC, edfloreshz approved these changes
I'll merge and delete the file later, I'm a bit short on time and I want the Flathub submission to proceed while I'm gone.

2024-09-29 03:37 UTC, merged